In [96]:
from __future__ import print_function, division
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

import torch
from torch import nn, optim
from torch.autograd import Variable
from torch.optim import Optimizer

import collections
import h5py, sys
import gzip
import os
import math

import pandas as pd


import pickle

import time
import torch.utils.data
from torchvision import transforms, datasets
import torchvision
import matplotlib

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

import matplotlib.pyplot as plt
import scipy.ndimage as ndim
import matplotlib.colors as mcolors

import time
import torch.utils.data
from torchvision import transforms, datasets
import torchvision
import argparse
import matplotlib
from src.Stochastic_Gradient_Langevin_Dynamics.model import *
import matplotlib.pyplot as plt

import torch
from torch import nn, optim
from torch.autograd import Variable
from torch.optim import Optimizer

import collections
import h5py, sys
import gzip
import os
import math

import pandas as pd




import time
import torch.utils.data
from torchvision import transforms, datasets
import torchvision
import matplotlib

from trian_predict import TP

from roc_data import roc

start = [0, 1]
end = [0, 1]

torch.cuda.empty_cache()

In [147]:
a = [[420,      0.494],
 [421,      0.494],
 [454,      0.479],
 [455,      0.479]]
a = np.array(a)
a

(array([420.   ,   0.494]),
 array([421.   ,   0.494]),
 array([454.   ,   0.479]),
 array([455.   ,   0.479]))

In [146]:
adata = a[a[:,0].argsort()][:,1]
print(adata)

[0.494 0.494 0.479 0.479]


In [138]:
aindex = a[a[:,0].argsort()][:,0]
print(aindex)

[420. 421. 454. 455.]


In [164]:
aaa = np.sort(np.unique(adata, return_index=True)[1])
len(aaa)

2

In [162]:
np.where(adata == adata[aaa[0]])

(array([0, 1], dtype=int64),)

In [163]:
aindex[np.where(adata == adata[aaa[0]])]

array([420., 421.])

In [166]:
adata[aaa[0]]

0.494

In [170]:
adata[np.sort(np.unique(adata, return_index=True)[1])]

array([0.494, 0.479])

In [171]:
np.shape(a)

(4, 2)

In [174]:
b = [[420,      0.494],
 [421],
 [454,      0.479],
 [455,      0.479]]

In [175]:
np.shape(b)

C:\Users\shuaizhouWang\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:1970: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = asarray(a).shape


(4,)

In [181]:
sum([len(i) for i in b])

7

In [182]:
os.path

<module 'ntpath' from 'C:\\Users\\shuaizhouWang\\anaconda3\\lib\\ntpath.py'>

In [ ]:
C2 = [[[24, 16], [5, 35]],
         [[27, 13], [8, 32]]]

C2all = [[[24,16], [5, 36]],
         [[24, 16], [5, 35]], 
         [[27, 13], [8, 32]], 
         [[27, 13], [8, 32]]]

In [ ]:
C2 = np.array(C2)
C2

In [ ]:
C2[0]

In [ ]:
C2all = np.array(C2all)
C2all

In [ ]:
CC = C2all[1]==C2[1]
print(CC)

In [ ]:
CC.any()

In [ ]:
CC.all()

In [ ]:
ppp=[]
for j in range(np.shape(C2)[0]):
    ll = []
    for k in range(np.shape(C2all)[0]):
        CC = C2[j] == C2all[k]
        if CC.all():
            ll.append(k)
            print(k)
    ppp.append([min(ll), max(ll)])
ppp

In [ ]:
k = {'fpr_SGLD': [0.325, 0.4], 'fpr_pSGLD': [0.125], 'fpr_SGHMC': [0.35 , 0.375], 'fpr_BBB': [0.44333333],
     'tpr_SGLD': [0.8, 0.875], 'tpr_pSGLD': [0.7], 'tpr_SGHMC': [0.625, 0.65], 'tpr_BBB': [0.74666667],
     'tnr_SGLD': [0.6, 0.675], 'tnr_pSGLD': [0.875], 'tnr_SGHMC': [0.625, 0.65], 'tnr_BBB': [0.55666667]}

In [ ]:
kk=[]
for i in k.values():
    kk.append(str(i))
    print(str(i))
    
kk = np.array(kk)
kk = np.reshape(kk,[3,4])
kk

In [ ]:
print(kk)

In [ ]:
df = pd.DataFrame(kk)
df

In [ ]:
C2 = [[[24, 16], [5, 35]],
         [[27, 13], [8, 32]]]

C2all = [[[24,16], [5, 35]],
         [[24, 16], [5, 35]], 
         [[27, 13], [8, 32]], 
         [[27, 13], [8, 32]]]